// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANmO5yFwgcnJVGGOlAQ-VLAgriMNcyv7Q',
    appId: '1:118693524308:web:a4f4bd8537f24680104ec1',
    messagingSenderId: '118693524308',
    projectId: 'flutter-template-e38b7',
    authDomain: 'flutter-template-e38b7.firebaseapp.com',
    storageBucket: 'flutter-template-e38b7.firebasestorage.app',
    measurementId: 'G-CWLYL0G35D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrkoaXKlf0BuW3-9QhWoOveLYFg3du9VI',
    appId: '1:118693524308:ios:bdaa08eac4d3b14c104ec1',
    messagingSenderId: '118693524308',
    projectId: 'flutter-template-e38b7',
    storageBucket: 'flutter-template-e38b7.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANmO5yFwgcnJVGGOlAQ-VLAgriMNcyv7Q',
    appId: '1:118693524308:web:6b9b90786b02ddff104ec1',
    messagingSenderId: '118693524308',
    projectId: 'flutter-template-e38b7',
    authDomain: 'flutter-template-e38b7.firebaseapp.com',
    storageBucket: 'flutter-template-e38b7.firebasestorage.app',
    measurementId: 'G-7TNF8KZW9T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrkoaXKlf0BuW3-9QhWoOveLYFg3du9VI',
    appId: '1:118693524308:ios:bdaa08eac4d3b14c104ec1',
    messagingSenderId: '118693524308',
    projectId: 'flutter-template-e38b7',
    storageBucket: 'flutter-template-e38b7.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0VgdJr_YtCgR5mjmVYWEag7fybH8druo',
    appId: '1:118693524308:android:cb351f358a8d5083104ec1',
    messagingSenderId: '118693524308',
    projectId: 'flutter-template-e38b7',
    storageBucket: 'flutter-template-e38b7.firebasestorage.app',
  );

}